---
engines:
  shellcheck:
    enabled: true
    checks:
      SC2001:
        enabled: false
      SC2076:
        enabled: false
      SC2086:
        enabled: false
      SC2119:
        enabled: false
      SC2128:
        enabled: false
      SC2154:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths: []
exclude_paths:
  - .t/
  - dev/
